--T?o b?ng
CREATE TABLE BAITAPHTTT1.XE
(
    MAXE varchar(3) constraint PK_XE primary key,
    BIENKS VARCHAR(9),
    MATUYEN VARCHAR(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
);

CREATE TABLE BAITAPHTTT1.TUYEN 
(
    MATUYEN VARCHAR(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR(3) not null,
    BENCUOI VARCHAR(3) not null,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
);

CREATE TABLE BAITAPHTTT1.KHACH
(
    MAKH VARCHAR(4) CONSTRAINT PK_KHACH PRIMARY KEY,
    HOTEN VARCHAR(20),
    GIOITINH VARCHAR(3),
    CMND NUMBER(11)
);

CREATE TABLE BAITAPHTTT1.VEXE 
(
    MATUYEN VARCHAR(4),
    MAKH VARCHAR(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN, MAKH, NGMUA)
);

--S?a ??nh d?ng ngày tháng 
ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
--Thêm khóa ngo?i
ALTER TABLE BAITAPHTTT1.XE ADD CONSTRAINT FK_XE_MATUYEN FOREIGN KEY(MATUYEN) REFERENCES BAITAPHTTT1.TUYEN(MATUYEN);
ALTER TABLE BAITAPHTTT1.VEXE ADD CONSTRAINT FK_VEXE_MATUYEN FOREIGN KEY(MATUYEN) REFERENCES BAITAPHTTT1.TUYEN(MATUYEN);
ALTER TABLE BAITAPHTTT1.VEXE ADD CONSTRAINT FK_VEXE_MAKH FOREIGN KEY(MAKH) REFERENCES BAITAPHTTT1.KHACH(MAKH);
--Câu 3
ALTER TABLE BAITAPHTTT1.TUYEN ADD CONSTRAINT CHECK_CAU3 CHECK (TGDK > 5 AND GIATUYEN > 200.000);
-- INSERT TABLE XE ---
INSERT INTO BAITAPHTTT1.XE VALUES
('X01', '52LD-4393','T11D',20,20);
INSERT INTO BAITAPHTTT1.XE VALUES
('X02', '59LD-7247','T32D',36,36);
INSERT INTO BAITAPHTTT1.XE VALUES
('X03','55LD-6850','T06F',15,15);
-- INSERT TABLE TUYEN ---
INSERT INTO BAITAPHTTT1.TUYEN VALUES
('T11A', 'SG','DL', 210.000,'26/12/2016',6);
INSERT INTO BAITAPHTTT1.TUYEN VALUES
('T32D', 'PT','SG', 120.000,'30/12/2016',4);
INSERT INTO BAITAPHTTT1.TUYEN VALUES
('T06F', 'NT','DNG', 225.000,'02/01/2017',7);
-- INSERT TABLE KHACH ---
INSERT INTO BAITAPHTTT1.KHACH VALUES
('KH01', 'Lam Van Ben','Nam', 655615896);
INSERT INTO BAITAPHTTT1.KHACH VALUES
('KH02', 'Duong Thi Luc','Nu', 275648642);
INSERT INTO BAITAPHTTT1.KHACH VALUES
('KH03', 'Hoang Thanh Tung','Nam', 456889143);
-- INSERT TABLE VEXE ---
INSERT INTO BAITAPHTTT1.VEXE VALUES
('T11D', 'KH01','20/12/2016', 210.000);
INSERT INTO BAITAPHTTT1.VEXE VALUES
('T32D', 'KH02','25/12/2016', 144.000);
INSERT INTO BAITAPHTTT1.VEXE VALUES
('T06F', 'KH03','30/12/2016', 270.000);

--Câu 5
SELECT * FROM BAITAPHTTT1.VEXE WHERE EXTRACT(MONTH FROM NGMUA) = 12 ORDER BY GIAVE DESC;
--Câu 6
SELECT MATUYEN FROM BAITAPHTTT1.VEXE WHERE EXTRACT(YEAR FROM NGMUA) = 2016 
    GROUP BY MATUYEN HAVING COUNT (MATUYEN) <= ALL
                                                    ( SELECT COUNT (MATUYEN) FROM BAITAPHTTT1.VEXE 
                                                      WHERE EXTRACT(YEAR FROM NGMUA) = 2016
                                                      GROUP BY MATUYEN);
--Câu 7
SELECT MATUYEN FROM BAITAPHTTT1.KHACH JOIN BAITAPHTTT1.VEXE
ON BAITAPHTTT1.KHACH.MAKH = BAITAPHTTT1.VEXE.MAKH
WHERE BAITAPHTTT1.KHACH.GIOITINH = 'Nam'
INTERSECT
SELECT MATUYEN FROM BAITAPHTTT1.KHACH JOIN BAITAPHTTT1.VEXE
ON BAITAPHTTT1.KHACH.MAKH = BAITAPHTTT1.VEXE.MAKH
WHERE BAITAPHTTT1.KHACH.GIOITINH = 'Nu';
--Câu 8
SELECT * FROM BAITAPHTTT1.KHACH KH
WHERE GIOITINH = 'NU' and NOT EXISTS (
SELECT * FROM BAITAPHTTT1.TUYEN TU
WHERE NOT EXISTS (
SELECT * FROM BAITAPHTTT1.VEXE VX
WHERE TU.MATUYEN = VX.MATUYEN AND KH.MAKH = VX.MAKH)
)
